### ISSUE TITLE
TemplateDoesNotExist Error

### ISSUE THREAD

**Issue by JuliusFiedler** [ackrep-org/ackrep_core#14]
When deploying the web server, all pages can be accessed as intended. Once the webhook of the CI is triggered, the following error message occurs:
````
[pid: 20|app: 0|req: 4/4] 172.19.0.2 () {48 vars in 747 bytes} [Fri Aug 12 09:11:57 2022] POST /webhook => generated 2438 bytes in 8359 msecs (HTTP/1.1 200) 5 headers in 173 bytes (1 switches on core 2)                                                                                                              
Internal Server Error: /webhook                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                         
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner                                                                                                       
    response = get_response(request)                                                                                                                                                                       
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response                                                                                                   
    response = response.render()                                                                                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 105, in render                                                                                                           
    self.content = self.rendered_content                                                                                                                                                                   
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content                                                                                                  
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 65, in resolve_template
    return get_template(template, using=self.using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: ackrep_web/webhook.html
````
Afterwards, every page produces the same error message.

Steps to reproduce:
- deploy server
- attach to ackrep-django container ( `docker attach $(docker ps -f name=ack -q)` )
- start ackrep_data CI run (doesnt matter if it fails as long as ist uploads results)
- wait for CI to trigger webhook and watch attached shell
- maybe try to load a web page

Restarting the container seems to fix the issue?

**Comment by JuliusFiedler** [comment]
problem was solved by fixing paralelly occuring git issue:
- ci_results yaml is downloaded as artifact into ci_res repo folder
- pull impossible since untracked file has same name
- git clean did **not** solve this
- → manually deleting all untracked files (since they are already commited by CI) fixed the git error and also this error 
see [commit](https://github.com/ackrep-org/ackrep_core/commit/e9f0f107fc116b63f47c774f93e68aeec323f912)
